name: airlink
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  line_icons: ^2.0.1
  flutter_blue: ^0.8.0
  cbor: ^5.0.1
  convert: ^3.0.1
  hex: ^0.2.0
  flutter_secure_storage: ^5.0.2
  flutter_dotenv: ^5.0.2
  http: ^0.13.4
  device_info_plus: ^3.2.2
  flutter_barcode_scanner: ^2.0.0
  location: ^4.3.0
  sqflite: ^2.0.2
  provider: ^6.0.3
  app_settings: ^4.1.8
  workmanager: ^0.5.0
  permission_handler: ^10.2.0
  timezone: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
