name: airlink
description: AirLink App with Clean Architecture.
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cbor: ^6.1.1
  convert: ^3.0.1
  hex: ^0.2.0
  flutter_secure_storage: ^6.0.0
  http: ^1.1.0
  device_info_plus: ^3.2.2
  flutter_barcode_scanner: ^2.0.0
  location: ^5.0.3
  provider: ^6.0.2
  app_settings: ^5.1.1
  permission_handler: ^11.0.0
  path_provider: ^2.0.15
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.0
  internet_connection_checker: ^1.0.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_blue_plus: ^1.16.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true